### ISSUE TITLE
[Question] What is the use case?

### ISSUE THREAD

**Issue by rockmandash** [lukeed/templite#1]
Hello, thank you for your library.
I want to know that since we have ES6 template literal.
What is this library's usage?
Is there any benefit in this way?
Thanks!

**Comment by lukeed** [comment]
Hey, 

Your template can be defined ahead of time & reused across varying data sources, whereas template literals are evaluated (and interpolated) immediately.

For context, I was using this for generating emails and for scaffolding configuration files. In both cases, the template was pre-defined (or stored in DB) and generated the desired output with new values every time it was invoked.

Hope that helps clear things up~!

**Comment by rockmandash** [comment]
Thank you!
Learned a lesson.

**Comment by lukeed** [comment]
No problem, glad to hear!
