### ISSUE TITLE
Empty folder when installing from npm

### ISSUE THREAD

**Issue by mhaagens** [lukeed/templite#5]

**Comment by lukeed** [comment]
Oh whoops, that's a first.. and embarrassing 😆

**Comment by lukeed** [comment]
I'm having an issue publishing on `npm` -- will get this out as soon as I hear back from them.

**Comment by lukeed** [comment]
Fixed in `1.1.0` -- apparently this module had an owner 3 years ago, so I had to skip all the `1.0.x` versions.

Thanks!
