### ISSUE TITLE
Question: Why reassign the offset?

### ISSUE THREAD

**Issue by mfbx9da4** [lukeed/templite#7]
![image](https://user-images.githubusercontent.com/1690659/106867705-d569c000-66c5-11eb-8292-6d277dd41d71.png)

I don't have any issue with this lib per-se. I'm more curious why you reassign the incoming offset to `mix`, the data. Why not declare `let y = mix`. Is this an optimization or a just to keep the code as small as possible?

**Comment by lukeed** [comment]
It's a golf/size-hack so that I don't have to declare a new variable – can just pull one out of the parameter list. Same thing is happening for `x`. The only value that actually matters within the replacer-function is `key`, which is why it's named. The other two are placeholders/throwaways :)
